### ISSUE TITLE
Running the app 100% local

### ISSUE THREAD

**Issue by Hantick** [momander/wheel-spinner#13]
Hi, I would like to host your wheel-spinner on my localhost and extend wheel to update names via API requests. Something like when I click the button i get all of the names from my local API. Is this possible to set up this app without firebase stuff etc. ?

**Comment by johnberry09** [comment]
I haven't yet looked at the code, however, I was able to run it locally just fine.
It was as simple as:

1. Clone the repo
2. npm install
3. bash build_dev.sh [or do the windows equivalent]
4. npx serve ./dist [or any static file server like http-server or caddy]

Probably the repo maintainer has made some changes over the last year so now it works locally.

**Comment by momander** [comment]
Thanks for outlining those steps, johnberry09! I added a section to the README to include them. Closing this issue now.
