### ISSUE TITLE
Winner dialog title overflow

### ISSUE THREAD

**Issue by m-apsolon** [momander/wheel-spinner#4]
Hi, 

Firstly, thanks for this wheel, my mother who's a kindergarten teacher, uses it often now that many children stay home. 

I entered a custom text to replace "the winner is... " with 100 characters and noticed  that the h5 runs out of the modal. If the _modal-card-title_ class had a width: 100%, the problem would be solved. 

<img width="800" alt="Screenshot 2020-05-05 at 17 27 51" src="https://user-images.githubusercontent.com/5763788/81084414-198d2180-8ef6-11ea-8efd-b1e1fb5d53b7.png">

<img width="873" alt="Screenshot 2020-05-05 at 17 27 57" src="https://user-images.githubusercontent.com/5763788/81084416-1c881200-8ef6-11ea-85bd-848b4916141b.png">

Could you find time to fix this? Would really appreciate. :-)

Thanks again!

**Comment by momander** [comment]
What an amazing bug report! Not only did you include clear screenshots, but also a proposed fix. Will apply your proposed fix and close this bug when done.

**Comment by m-apsolon** [comment]
Thanks! :)

**Comment by momander** [comment]
This has been fixed on wheelofnames.com, in version 41. Look for the version number on the lower right on the page. Do a [hard reload](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) to get the latest version.

Thank you for the bug report!
